Fix apk['antiFeatures']['DisabledAlgorithm']
$ grep 'archive_older:' config.yml
archive_older: 3
$
$ /opt/fdroidserver/fdroid update --verbose
[...]
2024-07-21 16:33:45,048 CRITICAL: Unknown exception found!
Traceback (most recent call last):
  File "/opt/fdroidserver/fdroid", line 22, in <module>
    fdroidserver.__main__.main()
  File "/opt/fdroidserver/fdroidserver/__main__.py", line 222, in main
    raise e
  File "/opt/fdroidserver/fdroidserver/__main__.py", line 203, in main
    mod.main()
  File "/opt/fdroidserver/fdroidserver/update.py", line 2715, in main
    archapks, cc = process_apks(apkcache, repodirs[1], knownapks,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fdroidserver/fdroidserver/update.py", line 2042, in process_apks
    (skip, apk, cachethis) = process_apk(apkcache, apkfilename, repodir, knownapks,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fdroidserver/fdroidserver/update.py", line 1953, in process_apk
    apk['antiFeatures'].update(['KnownVuln', 'DisabledAlgorithm'])  # TODO
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: dictionary update sequence element #0 has length 9; 2 is required